Repository xiaoyang-sde/reflare, pull requests merged in 2021-12, with the labels that each got.

#212 Implement content replacement
  src/index.ts
  src/replace.ts
  tsconfig.json
  types/proxy.ts
  types/replace.ts
Labels: enhancement

#237 Bump eslint from 7.32.0 to 8.5.0
  .eslintrc.js
  package-lock.json
  package.json
  src/load-balancing.ts
  src/storage.ts
  tsconfig.json
Labels: dependencies

#238 Bump @cloudflare/workers-types from 2.2.2 to 3.3.0
  .github/workflows/node.yml
  package-lock.json
  package.json
  src/firewall.ts
  tsconfig.json
Labels: dependencies

#239 Improve the options and logics of content replacement
  src/replace.ts
  types/replace.ts
Labels: enhancement

#240 Fix invalid badges and redirected links in README.md
  README.md
Labels: documentation
