Repository xiaoyang-sde/reflare, pull requests merged in 2021-09, with the labels that each got.

#168 Implement Cloudflare Workers KV
  src/index.ts
  src/storage.ts
  tests/cors.test.ts
  tests/firewall.test.ts
  tests/headers.test.ts
  tests/load-balancing.test.ts
  tests/storage.test.ts
  types/middleware.ts
  types/storage.ts
Labels: enhancement

#173 Write documentation for load balancing options
  README.md
  package-lock.json
  package.json
Labels: documentation

#177 Bump TypeScript from 4.3.5 to 4.4.2
  package-lock.json
  package.json
  src/load-balancing.ts
  tests/firewall.test.ts
  webpack.config.js
Labels: dependencies
